-
  name:  'Available forms'
  uriPattern: 'neos/management/formbuilder/list'
  defaults:
    '@package':    'SimplyAdmire.Neos.FormBuilderBundle'
    '@controller': 'Form'
    '@action':     'index'
    '@format':     'json'

-
  name:  'FormBuilder with controller and action'
  uriPattern: 'neos/management/formbuilder/{@controller}(/{@action})'
  defaults:
    '@package':    'TYPO3.FormBuilder'
    '@controller': 'FormManager'
    '@action':     'index'
    '@format':     'html'
  appendExceedingArguments: TRUE

-
  name:  'FormBuilder with controller and action and formPersistenceIdentifier'
  uriPattern: 'neos/management/formbuilder/{@controller}/{@action}/{formPersistenceIdentifier}(/{presetName})'
  defaults:
    '@package':    'TYPO3.FormBuilder'
    '@controller': 'FormManager'
    '@action':     'index'
    '@format':     'html'
  appendExceedingArguments: TRUE
