TYPO3:
  Neos:
    modules:
      management:
        submodules:
          formbuilder:
            label: 'Form Builder'
            controller: '\TYPO3\FormBuilder\Controller\FormManagerController'
            description: 'Form Builder'
            icon: 'icon-edit'
            resource: 'TYPO3_FormBuilder_FormManager'
    userInterface:
      requireJsPathMapping:
        'SimplyAdmire.Neos.FormBuilderBundle/Inspector/Editors': 'resource://SimplyAdmire.Neos.FormBuilderBundle/Public/Scripts/Inspector/Editors/'

  Form:
    presets:
      default:
        finisherPresets:
          'SimplyAdmire.Neos.FormBuilderBundle:Email':
            implementationClassName: 'SimplyAdmire\Neos\FormBuilderBundle\Finishers\EmailFinisher'
          'SimplyAdmire.Neos.FormBuilderBundle:NodeRedirect':
            implementationClassName: 'SimplyAdmire\Neos\FormBuilderBundle\Finishers\NodeRedirectFinisher'
        formElementTypes:
          'TYPO3.Form:Form':
            formBuilder:
              editors:
                finishers:
                  availableFinishers:
                    'SimplyAdmire.Neos.FormBuilderBundle:Email':
                      label: 'Send Email (FormBuilder bundle)'
                      viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.FinisherEditor.FormBuilderBundleEmailFinisherEditor'
                    'SimplyAdmire.Neos.FormBuilderBundle:NodeRedirect':
                      label: 'Node Redirect (FormBuilder bundle)'
                      viewName: 'TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.FinisherEditor.FormBuilderBundleNodeRedirectFinisherEditor'

  FormBuilder:
    javaScripts:
      formBuilderBundle:
        sorting: 120
        files: ['resource://SimplyAdmire.Neos.FormBuilderBundle/Public/Scripts/FormBuilder/finishers.js']
    handlebarsTemplates:
      # Finisher Editors
      Finisher-FormBuilderBundleEmailEditor: resource://SimplyAdmire.Neos.FormBuilderBundle/Private/FormBuilderTemplates/Finisher/EmailEditor.html
      Finisher-FormBuilderBundleNodeRedirectEditor: resource://SimplyAdmire.Neos.FormBuilderBundle/Private/FormBuilderTemplates/Finisher/NodeRedirectEditor.html