Neos:
  Neos:
    modules:
      management:
        submodules:
          formbuilder:
            label: 'Form Builder'
            controller: TYPO3\FormBuilder\Controller\FormManagerController
            description: 'Form Builder'
            icon: icon-edit
            privilegeTarget: TYPO3_FormBuilder_FormManager
    userInterface:
      requireJsPathMapping:
        SimplyAdmire.Neos.FormBuilderBundle/Inspector/Editors: 'resource://SimplyAdmire.Neos.FormBuilderBundle/Public/Scripts/Inspector/Editors/'
  Form:
    presets:
      default:
        finisherPresets:
          'SimplyAdmire.Neos.FormBuilderBundle:Email':
            implementationClassName: SimplyAdmire\Neos\FormBuilderBundle\Finishers\EmailFinisher
          'SimplyAdmire.Neos.FormBuilderBundle:NodeRedirect':
            implementationClassName: SimplyAdmire\Neos\FormBuilderBundle\Finishers\NodeRedirectFinisher
        formElementTypes:
          'TYPO3.Form:Form':
            formBuilder:
              editors:
                finishers:
                  availableFinishers:
                    'SimplyAdmire.Neos.FormBuilderBundle:Email':
                      label: 'Send Email (FormBuilder bundle)'
                      viewName: TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.FinisherEditor.FormBuilderBundleEmailFinisherEditor
                    'SimplyAdmire.Neos.FormBuilderBundle:NodeRedirect':
                      label: 'Node Redirect (FormBuilder bundle)'
                      viewName: TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.FinisherEditor.FormBuilderBundleNodeRedirectFinisherEditor
                    'TYPO3.Form:Confirmation':
                      label: 'Confirmation (FormBuilder bundle)'
                      viewName: TYPO3.FormBuilder.View.ElementOptionsPanel.Editor.FinisherEditor.FormBuilderBundleConfirmationFinisherEditor
  FormBuilder:
    javaScripts:
      formBuilderBundle:
        sorting: 120
        files:
          - 'resource://SimplyAdmire.Neos.FormBuilderBundle/Public/Scripts/Library/rangy-core.js'
          - 'resource://SimplyAdmire.Neos.FormBuilderBundle/Public/Scripts/Library/hallo.js'
          - 'resource://SimplyAdmire.Neos.FormBuilderBundle/Public/Scripts/FormBuilder/finishers.js'
    stylesheets:
      formBuilderBundle:
        sorting: 120
        files:
          - 'resource://SimplyAdmire.Neos.FormBuilderBundle/Public/Styles/ui/jquery-ui-1.8.16.custom.css'
          - 'resource://SimplyAdmire.Neos.FormBuilderBundle/Public/Styles/formbuilder.css'
    handlebarsTemplates:
      Finisher-FormBuilderBundleEmailEditor: 'resource://SimplyAdmire.Neos.FormBuilderBundle/Private/FormBuilderTemplates/Finisher/EmailEditor.html'
      Finisher-FormBuilderBundleNodeRedirectEditor: 'resource://SimplyAdmire.Neos.FormBuilderBundle/Private/FormBuilderTemplates/Finisher/NodeRedirectEditor.html'
      Finisher-TYPO3FormConfirmationEditor: 'resource://SimplyAdmire.Neos.FormBuilderBundle/Private/FormBuilderTemplates/Finisher/ConfirmationEditor.html'
