TYPO3:
  Neos:
    modules:
      management:
        submodules:
          formbuilder:
            label: 'Form Builder'
            controller: '\TYPO3\FormBuilder\Controller\FormManagerController'
            description: 'Form Builder'
            icon: 'icon-edit'
            resource: 'TYPO3_FormBuilder_FormManager'
    userInterface:
      requireJsPathMapping:
        'SimplyAdmire.Neos.FormBuilderBundle/Inspector/Editors': 'resource://SimplyAdmire.Neos.FormBuilderBundle/Public/Scripts/Inspector/Editors/'

  Form:
    presets:
      default:
        finisherPresets:
          'SimplyAdmire.Neos.FormBuilderBundle:Email':
            implementationClassName: 'SimplyAdmire\Neos\FormBuilderBundle\Finishers\EmailFinisher'
